# Generated by Django 4.2.3 on 2023-08-17 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(null=True)),
                ('subscriber_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='online_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedarticle',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userWhoLikedTheArticle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
