# Generated by Django 4.2.3 on 2023-09-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_articlecomment_commentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriber_person',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
